# -*- coding: utf-8 -*-
"""bq_1_for_powerbi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17W-ryzZMInp-ivLjvWX1JdlUWmX21LCa
"""

# Export chart datapoints to Excel (for PowerBI)
# Use with bq_1_caculation_modelling.ipynb


# Order time-of-day
tod_order = ["Morning", "Afternoon", "Evening", "Night"]
summary["start_time_of_day"] = pd.Categorical(
    summary["start_time_of_day"], categories=tod_order, ordered=True
)
summary = summary.sort_values(["start_time_of_day", "bike_model"]).reset_index(drop=True)

# Add extra columns that are useful for external charts
summary["ci95_lower"] = summary["mean"] - summary["ci95"]
summary["ci95_upper"] = summary["mean"] + summary["ci95"]
summary["duration_unit"] = "minutes"
summary["ci_level"] = "95%"

# clean column names for BI tools
export_df = summary.rename(columns={
    "start_time_of_day": "time_of_day",
    "bike_model": "bike_type",
    "mean": "avg_duration_min",
    "count": "n_trips",
    "std": "std_duration_min",
    "se": "se_duration_min",
    "ci95": "ci95_halfwidth_min"
})

# Keep a clear column order
export_df = export_df[[
    "time_of_day",
    "bike_type",
    "avg_duration_min",
    "ci95_halfwidth_min",
    "ci95_lower",
    "ci95_upper",
    "n_trips",
    "std_duration_min",
    "se_duration_min",
    "duration_unit",
    "ci_level"
]]

# Save to Excel
out_path = "/content/drive/MyDrive/TfL files/CLEANED/bq_1_for_powerbi.xlsx"
export_df.to_excel(out_path, index=False)

display(export_df.head(10))