# -*- coding: utf-8 -*-
"""bq_1_caculation_modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vj7UYMJCcGTFvsbXZGFOXjwf63zxuUni
"""

# Business Question 1 - ANOVA Test
# Dataset used: Cleaned JDE 2025 File (JDE_2025_cleanedv2.csv)
# Figure 3, 4, 5, 9
# Code done in Google Colab

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.formula.api import ols
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/TfL files/CLEANED/JDE_2025_cleanedv2.csv")
df = df.rename(columns={"total_duration_(ms)": "total_duration_ms"})

df = df.dropna(subset=["total_duration_ms", "bike_model", "start_time_of_day"])
df["bike_model"] = df["bike_model"].astype("category")
df["start_time_of_day"] = df["start_time_of_day"].astype("category")

# Two-way ANOVA with interaction
model = ols("total_duration_ms ~ C(start_time_of_day) * C(bike_model)", data=df).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print(anova_table)

# Visualisation: mean duration (minutes) by time_of_day, split by bike type
plot_df = df.copy()
plot_df["duration_min"] = plot_df["total_duration_ms"] / 60000

# Compute mean and 95% CI
g = plot_df.groupby(["start_time_of_day", "bike_model"])["duration_min"]
summary = g.agg(["mean", "count", "std"]).reset_index()
summary["se"] = summary["std"] / np.sqrt(summary["count"])
summary["ci95"] = 1.96 * summary["se"]

# Order time-of-day
tod_order = ["Morning", "Afternoon", "Evening", "Night"]
summary["start_time_of_day"] = pd.Categorical(summary["start_time_of_day"], categories=tod_order, ordered=True)
summary = summary.sort_values("start_time_of_day")

# Build grouped bars
cats = tod_order
bike_types = ["classic_bike", "e_bike"]

x = np.arange(len(cats))
width = 0.35

means_classic = []
cis_classic = []
means_ebike = []
cis_ebike = []

for c in cats:
    row_c = summary[(summary["start_time_of_day"] == c) & (summary["bike_model"] == "classic_bike")]
    row_e = summary[(summary["start_time_of_day"] == c) & (summary["bike_model"] == "e_bike")]

    means_classic.append(row_c["mean"].iloc[0] if len(row_c) else np.nan)
    cis_classic.append(row_c["ci95"].iloc[0] if len(row_c) else np.nan)

    means_ebike.append(row_e["mean"].iloc[0] if len(row_e) else np.nan)
    cis_ebike.append(row_e["ci95"].iloc[0] if len(row_e) else np.nan)

# bar graph for classic bike only

plt.figure(figsize=(9, 4.5))
plt.bar(x - width/2, means_classic, width, yerr=cis_classic, capsize=4, label="classic_bike", color="tab:blue")

plt.xticks(x, cats)
plt.ylabel("Mean trip duration (minutes)")
plt.title("Trip Duration’s Mean of Classic Bikes by Time of Day  (95% CI)")
plt.legend()
plt.tight_layout()
plt.show()

# bar graph for e-bike only

plt.figure(figsize=(9, 4.5))
plt.bar(x + width/2, means_ebike, width, yerr=cis_ebike, capsize=4, label="e_bike",color="tab:orange")

plt.xticks(x, cats)
plt.ylabel("Mean trip duration (minutes)")
plt.title("Trip Duration’s Mean of E-Bikes by Time of Day  (95% CI)")
plt.legend()
plt.tight_layout()
plt.show()

# bar graph for both

plt.figure(figsize=(9, 4.5))
plt.bar(x - width/2, means_classic, width, yerr=cis_classic, capsize=4, label="classic_bike", color="tab:blue")
plt.bar(x + width/2, means_ebike, width, yerr=cis_ebike, capsize=4, label="e_bike",color="tab:orange")

plt.xticks(x, cats)
plt.ylabel("Mean trip duration (minutes)")
plt.title("Trip Duration’s Mean by Time of Day and Bike Type (95% CI)")
plt.legend()
plt.tight_layout()
plt.show()