# -*- coding: utf-8 -*-
"""data_compiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyFEXsoMv8hvrts81kgzxX9YTsAYUHqQ
"""

# Data Consolidation
# Dataset used: Raw Journey Data Extract files from 411-120
# Code done in Google Colab

import pandas as pd

# 1 Link raw files

df1 = pd.read_csv("/content/drive/MyDrive/TfL files/JDE 2025 files/411JourneyDataExtract01Jan2025-14Jan2025.csv")
df2 = pd.read_csv("/content/drive/MyDrive/TfL files/JDE 2025 files/412JourneyDataExtract15Jan2025-31Jan2025.csv")
df3 = pd.read_csv("/content/drive/MyDrive/TfL files/JDE 2025 files/413JourneyDataExtract01Feb2025-14Feb2025.csv")
df4 = pd.read_csv("/content/drive/MyDrive/TfL files/JDE 2025 files/414JourneyDataExtract15Feb2025-28Feb2025.csv")
df5 = pd.read_csv("/content/drive/MyDrive/TfL files/JDE 2025 files/415JourneyDataExtract01Mar2025-14Mar2025.csv")
df6 = pd.read_csv("/content/drive/MyDrive/TfL files/JDE 2025 files/416JourneyDataExtract15Mar2025-31Mar2025.csv")
df7 = pd.read_csv("/content/drive/MyDrive/TfL files/JDE 2025 files/417JourneyDataExtract01Apr2025-14Apr2025.csv")
df8 = pd.read_csv("/content/drive/MyDrive/TfL files/JDE 2025 files/418JourneyDataExtract15Apr2025-30Apr2025.csv")
df9 = pd.read_csv("/content/drive/MyDrive/TfL files/JDE 2025 files/419JourneyDataExtract01May2025-14May2025.csv")
df10 = pd.read_csv("/content/drive/MyDrive/TfL files/JDE 2025 files/420JourneyDataExtract14May2025-31May2025.csv")

# 2 Concat all raw file

combined_df = pd.concat([df1, df2, df3,df4,df5,df6,df7,df8,df9,df10], ignore_index=True)

# 3 Export file

combined_df.to_csv("/content/drive/MyDrive/TfL files/CLEANED/JDE_2025_compiled.csv", index=False)